/**
 * Mock Indian Holidays 2025–2026 — National + Major State Holidays
 * Used as fallback when Calendarific API is unavailable
 */
export const MOCK_HOLIDAYS_2025 = [
  {
    name: 'Republic Day',
    date: { iso: '2025-01-26' },
    type: ['National holiday'],
    description: 'Republic Day celebrates the adoption of the Constitution of India.',
    primary_type: 'National holiday',
  },
  {
    name: 'Maha Shivaratri',
    date: { iso: '2025-02-26' },
    type: ['Gazetted Holiday'],
    description: 'Hindu festival dedicated to Lord Shiva.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Holi',
    date: { iso: '2025-03-14' },
    type: ['Gazetted Holiday'],
    description: 'Festival of colours celebrating spring.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Good Friday',
    date: { iso: '2025-04-18' },
    type: ['Gazetted Holiday'],
    description: 'Christian observance of the crucifixion of Jesus Christ.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Dr. Ambedkar Jayanti',
    date: { iso: '2025-04-14' },
    type: ['Gazetted Holiday'],
    description: 'Birth anniversary of Dr. B.R. Ambedkar.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Ram Navami',
    date: { iso: '2025-04-06' },
    type: ['Gazetted Holiday'],
    description: 'Hindu festival celebrating the birth of Lord Rama.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Eid ul-Fitr',
    date: { iso: '2025-03-31' },
    type: ['Gazetted Holiday'],
    description: 'Islamic festival marking the end of Ramadan.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'May Day / Labour Day',
    date: { iso: '2025-05-01' },
    type: ['Gazetted Holiday'],
    description: 'International Workers\' Day.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Buddha Purnima',
    date: { iso: '2025-05-12' },
    type: ['Gazetted Holiday'],
    description: 'Celebrates the birth of Gautama Buddha.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Eid ul-Adha (Bakrid)',
    date: { iso: '2025-06-07' },
    type: ['Gazetted Holiday'],
    description: 'Islamic festival of sacrifice.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Muharram',
    date: { iso: '2025-07-06' },
    type: ['Gazetted Holiday'],
    description: 'Islamic New Year observance.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Independence Day',
    date: { iso: '2025-08-15' },
    type: ['National holiday'],
    description: 'India\'s Independence Day.',
    primary_type: 'National holiday',
  },
  {
    name: 'Janmashtami',
    date: { iso: '2025-08-16' },
    type: ['Gazetted Holiday'],
    description: 'Celebrates the birth of Lord Krishna.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Milad un-Nabi',
    date: { iso: '2025-09-05' },
    type: ['Gazetted Holiday'],
    description: 'Birthday of Prophet Muhammad.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Mahatma Gandhi Jayanti',
    date: { iso: '2025-10-02' },
    type: ['National holiday'],
    description: 'Birth anniversary of Mahatma Gandhi.',
    primary_type: 'National holiday',
  },
  {
    name: 'Dussehra',
    date: { iso: '2025-10-02' },
    type: ['Gazetted Holiday'],
    description: 'Victory of good over evil; celebrated across India.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Diwali',
    date: { iso: '2025-10-20' },
    type: ['Gazetted Holiday'],
    description: 'Festival of lights.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Guru Nanak Jayanti',
    date: { iso: '2025-11-05' },
    type: ['Gazetted Holiday'],
    description: 'Birth of Guru Nanak Dev Ji.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Christmas',
    date: { iso: '2025-12-25' },
    type: ['Gazetted Holiday'],
    description: 'Christian celebration of the birth of Jesus Christ.',
    primary_type: 'Gazetted Holiday',
  },
  // --- 2026 holidays ---
  {
    name: 'Republic Day',
    date: { iso: '2026-01-26' },
    type: ['National holiday'],
    description: 'Republic Day 2026.',
    primary_type: 'National holiday',
  },
  {
    name: 'Maha Shivaratri',
    date: { iso: '2026-02-15' },
    type: ['Gazetted Holiday'],
    description: 'Hindu festival dedicated to Lord Shiva.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Holi',
    date: { iso: '2026-03-03' },
    type: ['Gazetted Holiday'],
    description: 'Festival of colours celebrating spring.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Ram Navami',
    date: { iso: '2026-03-26' },
    type: ['Gazetted Holiday'],
    description: 'Hindu festival celebrating the birth of Lord Rama.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Eid ul-Fitr',
    date: { iso: '2026-03-20' },
    type: ['Gazetted Holiday'],
    description: 'Islamic festival marking the end of Ramadan.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Good Friday',
    date: { iso: '2026-04-03' },
    type: ['Gazetted Holiday'],
    description: 'Christian observance of the crucifixion of Jesus Christ.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Dr. Ambedkar Jayanti',
    date: { iso: '2026-04-14' },
    type: ['Gazetted Holiday'],
    description: 'Birth anniversary of Dr. B.R. Ambedkar.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Buddha Purnima',
    date: { iso: '2026-05-31' },
    type: ['Gazetted Holiday'],
    description: 'Celebrates the birth of Gautama Buddha.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Eid ul-Adha (Bakrid)',
    date: { iso: '2026-05-27' },
    type: ['Gazetted Holiday'],
    description: 'Islamic festival of sacrifice.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Independence Day',
    date: { iso: '2026-08-15' },
    type: ['National holiday'],
    description: 'India\'s Independence Day.',
    primary_type: 'National holiday',
  },
  {
    name: 'Janmashtami',
    date: { iso: '2026-08-06' },
    type: ['Gazetted Holiday'],
    description: 'Celebrates the birth of Lord Krishna.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Mahatma Gandhi Jayanti',
    date: { iso: '2026-10-02' },
    type: ['National holiday'],
    description: 'Birth anniversary of Mahatma Gandhi.',
    primary_type: 'National holiday',
  },
  {
    name: 'Dussehra',
    date: { iso: '2026-10-19' },
    type: ['Gazetted Holiday'],
    description: 'Victory of good over evil.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Diwali',
    date: { iso: '2026-11-08' },
    type: ['Gazetted Holiday'],
    description: 'Festival of lights.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Guru Nanak Jayanti',
    date: { iso: '2026-11-24' },
    type: ['Gazetted Holiday'],
    description: 'Birth of Guru Nanak Dev Ji.',
    primary_type: 'Gazetted Holiday',
  },
  {
    name: 'Christmas',
    date: { iso: '2026-12-25' },
    type: ['Gazetted Holiday'],
    description: 'Christmas Day.',
    primary_type: 'Gazetted Holiday',
  },
];
