/**
 * Indian States with ISO 3166-2:IN codes for Calendarific API
 */
export const INDIAN_STATES = [
  { label: 'Andhra Pradesh', value: 'in-ap', code: 'AP' },
  { label: 'Arunachal Pradesh', value: 'in-ar', code: 'AR' },
  { label: 'Assam', value: 'in-as', code: 'AS' },
  { label: 'Bihar', value: 'in-br', code: 'BR' },
  { label: 'Chhattisgarh', value: 'in-ct', code: 'CT' },
  { label: 'Delhi', value: 'in-dl', code: 'DL' },
  { label: 'Goa', value: 'in-ga', code: 'GA' },
  { label: 'Gujarat', value: 'in-gj', code: 'GJ' },
  { label: 'Haryana', value: 'in-hr', code: 'HR' },
  { label: 'Himachal Pradesh', value: 'in-hp', code: 'HP' },
  { label: 'Jharkhand', value: 'in-jh', code: 'JH' },
  { label: 'Karnataka', value: 'in-ka', code: 'KA' },
  { label: 'Kerala', value: 'in-kl', code: 'KL' },
  { label: 'Madhya Pradesh', value: 'in-mp', code: 'MP' },
  { label: 'Maharashtra', value: 'in-mh', code: 'MH' },
  { label: 'Manipur', value: 'in-mn', code: 'MN' },
  { label: 'Meghalaya', value: 'in-ml', code: 'ML' },
  { label: 'Mizoram', value: 'in-mz', code: 'MZ' },
  { label: 'Nagaland', value: 'in-nl', code: 'NL' },
  { label: 'Odisha', value: 'in-or', code: 'OR' },
  { label: 'Punjab', value: 'in-pb', code: 'PB' },
  { label: 'Rajasthan', value: 'in-rj', code: 'RJ' },
  { label: 'Sikkim', value: 'in-sk', code: 'SK' },
  { label: 'Tamil Nadu', value: 'in-tn', code: 'TN' },
  { label: 'Telangana', value: 'in-tg', code: 'TG' },
  { label: 'Tripura', value: 'in-tr', code: 'TR' },
  { label: 'Uttar Pradesh', value: 'in-up', code: 'UP' },
  { label: 'Uttarakhand', value: 'in-ut', code: 'UT' },
  { label: 'West Bengal', value: 'in-wb', code: 'WB' },
  { label: 'Andaman & Nicobar', value: 'in-an', code: 'AN' },
  { label: 'Chandigarh', value: 'in-ch', code: 'CH' },
  { label: 'Dadra & Nagar Haveli', value: 'in-dn', code: 'DN' },
  { label: 'Daman & Diu', value: 'in-dd', code: 'DD' },
  { label: 'Jammu & Kashmir', value: 'in-jk', code: 'JK' },
  { label: 'Ladakh', value: 'in-la', code: 'LA' },
  { label: 'Lakshadweep', value: 'in-ld', code: 'LD' },
  { label: 'Puducherry', value: 'in-py', code: 'PY' },
];

/**
 * Reverse geocode state name to ISO code mapping
 */
export const STATE_NAME_TO_ISO = {
  'andhra pradesh': 'in-ap',
  'arunachal pradesh': 'in-ar',
  'assam': 'in-as',
  'bihar': 'in-br',
  'chhattisgarh': 'in-ct',
  'delhi': 'in-dl',
  'new delhi': 'in-dl',
  'goa': 'in-ga',
  'gujarat': 'in-gj',
  'haryana': 'in-hr',
  'himachal pradesh': 'in-hp',
  'jharkhand': 'in-jh',
  'karnataka': 'in-ka',
  'kerala': 'in-kl',
  'madhya pradesh': 'in-mp',
  'maharashtra': 'in-mh',
  'manipur': 'in-mn',
  'meghalaya': 'in-ml',
  'mizoram': 'in-mz',
  'nagaland': 'in-nl',
  'odisha': 'in-or',
  'orissa': 'in-or',
  'punjab': 'in-pb',
  'rajasthan': 'in-rj',
  'sikkim': 'in-sk',
  'tamil nadu': 'in-tn',
  'telangana': 'in-tg',
  'tripura': 'in-tr',
  'uttar pradesh': 'in-up',
  'uttarakhand': 'in-ut',
  'west bengal': 'in-wb',
  'jammu and kashmir': 'in-jk',
  'jammu & kashmir': 'in-jk',
  'ladakh': 'in-la',
  'puducherry': 'in-py',
  'pondicherry': 'in-py',
  'chandigarh': 'in-ch',
  'andaman and nicobar': 'in-an',
  'andaman & nicobar': 'in-an',
  'lakshadweep': 'in-ld',
  'dadra and nagar haveli': 'in-dn',
  'daman and diu': 'in-dd',
};
